#!/usr/bin/env python3
"""
Build real test blueprints for Y-spanning and Z-spanning in-game import validation,
using h3_generator.py. Same approach as build_xspan_import_test.py (which deployed
successfully on 2026-06-19): clone a real working export verbatim and surgically
replace only the h3 entries' voxel.data with from-scratch generated bytes.
See feedback_import_test_envelope memory for why this matters (hand-rolled
Model.Size/version envelopes break the server's migrate/copyTo step even when the
voxel scan bytes themselves are correct).
"""
import sys
import os
import json
import base64
import struct
import lz4.block

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import h3_generator as g
import generate_hollow_cube as ghc

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)


def find_export(num):
    for d in ('exports', 'exports/archive'):
        p = os.path.join(ROOT, d, f'{num}_export.blueprint')
        if os.path.exists(p):
            return p
    return None


def decode_chunk_from_blob(blob):
    unc = struct.unpack('<I', blob[4:8])[0]
    dec = lz4.block.decompress(blob[12:], uncompressed_size=unc)
    idx = dec.find(b'Debug1')
    return dec[64:idx - 13], int.from_bytes(dec[idx - 13:idx - 9], 'little')


def mat_section_for(real_mc):
    mat_info = ghc.MATERIALS_INFO['hcCarbon']
    return ghc._mat_section(mat_info[1], mat_info[0], real_mc)


def replace_h3_entry(e, gen_scan, real_mc):
    key = (e['x']['$numberLong'], e['y']['$numberLong'], e['z']['$numberLong'])
    mat = mat_section_for(real_mc)
    new_blob = ghc._blob(ghc._hdr(*key) + gen_scan + mat)
    e['records']['voxel']['data']['$binary'] = ghc._b64(new_blob)


def build_yspan():
    export_num = 1658
    path = find_export(export_num)
    with open(path) as f:
        bp = json.load(f)

    pos1_map = {(2, 1, 2): 29, (2, 2, 2): 19, (1, 1, 2): 335, (1, 2, 2): 325}
    base_map = {
        (2, 1, 2): ('212', 1, 631), (2, 2, 2): ('222', 161, 727),
        (1, 1, 2): ('112', 33, 599), (1, 2, 2): ('122', 193, 695),
    }

    n_replaced = 0
    for e in bp['VoxelData']:
        if e['h'] != 3:
            continue
        key = (e['x']['$numberLong'], e['y']['$numberLong'], e['z']['$numberLong'])
        if key not in base_map:
            continue
        real_blob = base64.b64decode(e['records']['voxel']['data']['$binary'])
        real_scan, real_mc = decode_chunk_from_blob(real_blob)

        role, base_own, base_mc = base_map[key]
        pos1 = pos1_map[key]
        gen_scan, gen_mc = g.generate_yspan_scan(role, base_own, base_mc, pos1)
        assert gen_scan == real_scan, f'h3{key} scan mismatch'
        assert gen_mc == real_mc, f'h3{key} mc mismatch'

        replace_h3_entry(e, gen_scan, real_mc)
        n_replaced += 1

    assert n_replaced == 4, f'expected 4, got {n_replaced}'
    out_path = os.path.join(HERE, 'yspan_import_test.blueprint')
    with open(out_path, 'w') as f:
        json.dump(bp, f)
    print(f'Y-spanning: sanity OK, {n_replaced} h3 entries substituted (from export {export_num}).')
    print(f'Written: {out_path} ({os.path.getsize(out_path)} bytes)')


def build_zspan():
    export_num = 1665
    path = find_export(export_num)
    with open(path) as f:
        bp = json.load(f)

    pos1_map = {(2, 1): 29, (2, 2): 19, (1, 1): 335, (1, 2): 325}
    base_map = {
        (2, 1): ('212', 1, 631), (2, 2): ('222', 161, 727),
        (1, 1): ('112', 33, 599), (1, 2): ('122', 193, 695),
    }

    # Precompute both cz sides per (cx,cy) role
    pair_cache = {}
    for (cx, cy), (role, base_own, base_mc) in base_map.items():
        pos1 = pos1_map[(cx, cy)]
        cz2_scan, cz2_mc, cz1_scan, cz1_mc = g.generate_zspan_farz_pair(role, base_own, base_mc, pos1)
        pair_cache[(cx, cy)] = {2: (cz2_scan, cz2_mc), 1: (cz1_scan, cz1_mc)}

    n_replaced = 0
    for e in bp['VoxelData']:
        if e['h'] != 3:
            continue
        cx, cy, cz = e['x']['$numberLong'], e['y']['$numberLong'], e['z']['$numberLong']
        if (cx, cy) not in pair_cache or cz not in (1, 2):
            continue
        real_blob = base64.b64decode(e['records']['voxel']['data']['$binary'])
        real_scan, real_mc = decode_chunk_from_blob(real_blob)

        gen_scan, gen_mc = pair_cache[(cx, cy)][cz]
        assert gen_scan == real_scan, f'h3({cx},{cy},{cz}) scan mismatch'
        assert gen_mc == real_mc, f'h3({cx},{cy},{cz}) mc mismatch'

        replace_h3_entry(e, gen_scan, real_mc)
        n_replaced += 1

    assert n_replaced == 8, f'expected 8, got {n_replaced}'
    out_path = os.path.join(HERE, 'zspan_import_test.blueprint')
    with open(out_path, 'w') as f:
        json.dump(bp, f)
    print(f'Z-spanning: sanity OK, {n_replaced} h3 entries substituted (from export {export_num}).')
    print(f'Written: {out_path} ({os.path.getsize(out_path)} bytes)')


if __name__ == '__main__':
    build_yspan()
    build_zspan()
